# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  utility_config = release
  assembler_config = release
endif
ifeq ($(config),debug)
  utility_config = debug
  assembler_config = debug
endif

PROJECTS := utility assembler

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

utility:
ifneq (,$(utility_config))
	@echo "==== Building utility ($(utility_config)) ===="
	@${MAKE} --no-print-directory -C . -f utility.make config=$(utility_config)
endif

assembler: utility
ifneq (,$(assembler_config))
	@echo "==== Building assembler ($(assembler_config)) ===="
	@${MAKE} --no-print-directory -C source/assembler -f Makefile config=$(assembler_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f utility.make clean
	@${MAKE} --no-print-directory -C source/assembler -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   utility"
	@echo "   assembler"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"