name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up GCC
      run: sudo apt-get install -y gcc make

    - name: Install Premake
      if: steps.cache-premake.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
        tar -xzvf premake-5.0.0-alpha16-linux.tar.gz
        sudo mv premake5 /usr/local/bin/        

    - name: Generate project files with premake5
      run: premake5 gmake

    - name: Build the project
      run: make config=debug

    - name: Run tests
      run: ./output/bin/test_runner/test_runner

    - name: Verify tests passed
      run: echo "Tests passed successfully!"

