name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get install -y gcc premake4 make

    - name: Generate project files with premake5
      run: premake5 gmake

    - name: Build the project
      run: make config=debug

    - name: Run tests
      run: ./output/bin/test_runner/test_runner

    - name: Verify tests passed
      run: echo "Tests passed successfully!"

